### ISSUE TITLE
dropdownMenuMode is required on Android

### ISSUE THREAD

**Issue by robertcabrera4871** [mpiannucci/react-native-context-menu-view#100]
Using the example app, only the purple box showed a menu. Removing the line `dropdownMenuMode={true}` made none of them function.

https://github.com/mpiannucci/react-native-context-menu-view/assets/42824688/06f72c2e-e490-4db8-97b6-eb4ca4ccc8b0

**Comment by mpiannucci** [comment]
I tested on main right now and had no issues with the android emulator. Please reopen if necessary!
