### ISSUE TITLE
Custom content in ContextMenu

### ISSUE THREAD

**Issue by ngondat97** [mpiannucci/react-native-context-menu-view#11]
![Simulator Screen Shot - iPhone 11 - 2020-07-29 at 16 45 11](https://user-images.githubusercontent.com/43341571/88785111-fef7db00-d1ba-11ea-9260-f3cc135abe6e.png)

After showing the context menu, I just want to display the image of the item.
How to customize content after showing context menu?

**Comment by mpiannucci** [comment]
This should be possible but it has to be added using native funcationality to display a custom `previewProvider`: 

https://github.com/mpiannucci/react-native-context-menu-view/blob/e517e4c181a60f7112c5d97ab0f4c170ea4bf6ea/ios/ContextMenuView.m#L41

**Comment by shelllogix** [comment]
@mpiannucci When will be ready custom previewProvider native functionality for using custom views?

**Comment by HrantAbrahamyan** [comment]
@mpiannucci @ngondat97 @maartenvanvliet @alessandrod @jacobp100  Hi guys, I want to know when will be ready custom previewProvider? Is lib maintained or we should look other solution?

**Comment by jacobp100** [comment]
I had a quick look at this. It's a little more involved, because we need to create a UIViewController just to wrap the view. There's a guide [here](https://kylebashour.com/posts/context-menu-guide).

I think for the API, we can have a `preview` parameter that takes a view.

```js
<ContextMenu preview={<Preview .../>}>
  <Content />
</ContextMenu>
```

To get this to work with React, we have to attach the preview as a child.

```js
const styles = StyleSheet.create({
  preview: {
    ...StyleSheet.absoluteFillObject,
    display: 'none',
  }
})

const ContextMenu = (props) => (
  <NativeContextMenu {…props}>
    {props.children}
    {props.preview != null ? (
      <View style={styles.preview}>
        {props.preview}
      </View>
    ) : null}
  </NativeContextMenu>
)
```

Then override `- (void)insertReactSubview:(UIView *)subview atIndex:(NSInteger)atIndex` & co. in the native code to handle the primary content vs. preview.

I'm happy to provide pointers if anyone wants to work on it.

**Comment by mpiannucci** [comment]
Thanks @jacobp100 

This library is maintained but as he says this is not super trivial and I am in the middle of some personal life stuff that is taking priority. I will try to look into it soon as possible but I can't promise a time for it to be done.

I am happy to help anyone add the functionality if they want to take a stab at it.

**Comment by HrantAbrahamyan** [comment]
@jacobp100 @mpiannucci Thanks!

**Comment by HrantAbrahamyan** [comment]
@jacobp100 @mpiannucci  Can I pass component as props to native ios side?

**Comment by jacobp100** [comment]
You'll need to pass components as children, or React won't mount them. See my JS example for how to add a prop as a child. `- (void)insertReactSubview` is called on the native side when a child is added.

**Comment by HrantAbrahamyan** [comment]
ok I understand, now we have two childs second is display none, could you tell me how can I get only the second child in native side ? I have all just I think need to change insertReactSubview native function, if you can send here this changed example, thats will be nice.

![image](https://user-images.githubusercontent.com/36418107/94153578-fefc1a80-fe8d-11ea-9d04-29ee59270a6a.png)
![image](https://user-images.githubusercontent.com/36418107/94154056-8d709c00-fe8e-11ea-82da-04a7f2345b72.png)

**Comment by jacobp100** [comment]
So the logic here is if the index is `0`, follow the current logic. But if the index is `1`, don't follow any of the existing logic, but instead store a reference to the view. Then when you make the context menu†, you can use the view.

One thing I'm thinking now is if the children is null, or a fragment, the `0`/`1` index idea breaks. If we just make a native `ContextMenuPreviewView`, that is just a plain UIView with no additional properties, we can just do a `[subview isKindOfClass:]` check, and that will be more reliable.

If you wanted to do this, just follow what happens in `ContextMenuView.h` and `ContextMenuView.m`, removing anything unrelated.

† `- (nullable UIContextMenuConfiguration *)contextMenuInteraction:(nonnull UIContextMenuInteraction *)interaction configurationForMenuAtLocation:(CGPoint)location  API_AVAILABLE(ios(13.0))`

**Comment by HrantAbrahamyan** [comment]
See I did custom view controller and its work fine, but here I manually create UIView and add subview, thats why I wanted to know is it possible pass component from RN to native side, if it was possible we will solve this problem very easy) 
![image](https://user-images.githubusercontent.com/36418107/94163917-77b4a400-fe99-11ea-9247-6b3522405570.png)

Thanks. I will try index solution.

**Comment by mrousavy** [comment]
Hey! I'm currently having the same problem, I want to highlight a chat cell.

Currently it has the default white background, which looks a bit weird:

<img src="https://user-images.githubusercontent.com/15199031/97885445-aa1eb000-1d27-11eb-8a4f-279d9d000b9b.png" width="55%">

Do you have any progress on this?

**Comment by jacobp100** [comment]
@mrousavy  Can you share the JSX you got for that?

**Comment by mrousavy** [comment]
@jacobp100 what do you mean exactly?

```jsx
return (
  <View style={[styles.container, style, containerStyle]} {...passThroughProps}>
    <ContextMenu actions={isSender ? CONTEXT_MENU_ACTIONS_ME : CONTEXT_MENU_ACTIONS_OTHER} onPress={onContextActionPressed}>
      <LinearGradient style={[styles.gradient, bubbleStyle]} colors={gradientColors}>
        {renderMessage()}
        <Text style={sentAtTextStyle}>{sentAtText}</Text>
      </LinearGradient>
    </ContextMenu>
  </View>
);
```

That's my message component, haven't played around with the native implementation yet to add support for a custom preview renderer..

**Comment by jacobp100** [comment]
Try,

```jsx
return (
  <ContextMenu
    style={[styles.container, style, containerStyle, { borderRadius: yourBorderRadius }]}
    {...passThroughProps}
    actions={isSender ? CONTEXT_MENU_ACTIONS_ME : CONTEXT_MENU_ACTIONS_OTHER}
    onPress={onContextActionPressed}
  >
    <LinearGradient style={[styles.gradient, bubbleStyle, { borderRadius: 0 }]} colors={gradientColors}>
      {renderMessage()}
      <Text style={sentAtTextStyle}>{sentAtText}</Text>
    </LinearGradient>
  </ContextMenu>
);
```

**Comment by mrousavy** [comment]
@jacobp100 sorry we just had a terror attack. Okay I tried the overflow hidden approach, but then the animation looks a bit weird:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/15199031/97979327-3c2dc380-1dcf-11eb-9f2f-ea54b4ca8742.gif)

**Comment by jacobp100** [comment]
Sorry to hear that. Hoping you and your loved ones are safe. Please don't feel rushed or obliged to get back to me!

I think maybe the issue of the animation can be fixed by using border radius twice.

```diff
 return (
   <ContextMenu
-    style={[styles.container, style, containerStyle, { borderRadius: yourBorderRadius, overflow: 'hidden' }]}
+    style={[styles.container, style, containerStyle, { borderRadius: yourBorderRadius }]}
     {...passThroughProps}
     actions={isSender ? CONTEXT_MENU_ACTIONS_ME : CONTEXT_MENU_ACTIONS_OTHER}
     onPress={onContextActionPressed}
   >
-    <LinearGradient style={[styles.gradient, bubbleStyle, { borderRadius: 0 }]} colors={gradientColors}>
+    <LinearGradient style={[styles.gradient, bubbleStyle, { borderRadius: yourBorderRadius }]} colors={gradientColors}>
       {renderMessage()}
       <Text style={sentAtTextStyle}>{sentAtText}</Text>
     </LinearGradient>
   </ContextMenu>
 );
```

I think for your case, you'll only need some tweaking to get the default preview working correctly. Even if we had support for the custom menu preview, I think you'd still want to use the default preview.

**Comment by mrousavy** [comment]
@jacobp100 all good, bunch of my friends evacuated and none of my close friends are hurt. unfortunately some people didn't get lucky, and I've heard of a girl loosing her 20 y/o boyfriend, can't even imagine that.

Anyways, let's not talk about that. When applying borderRadius to the view inside (`<LinearGradient>`) as well, then the issue with the white background in the preview comes up again. :/ 

I've played around with firing an event when the preview is about to open and setting my `borderRadius` to `0` then, but that's a wacky solution...

**Comment by jacobp100** [comment]
Interesting. I think the animation changes the border radius applied.

I played around with iMessage, and those chat bubbles definitely don't change shape when you open the context menu. The only way I can see them doing that is by using the `mask` property on UIView.

So I wonder if using [react-native-masked-view](https://github.com/react-native-masked-view/react-native-masked-view) might just work. E.g.,

```jsx
<MaskedView maskElement={<View style={{ width: "100%", height: "100%", backgroundColor: 'black', borderRadius: something }} />}>
  <ContextMenu {...contextMenuProps}>
    <LinearGradient style={{ borderRadius: 0}}>
      {content}
    </LinearGradient>
  </ContextMenu>
</MaskedView>
```

**Comment by mrousavy** [comment]
@jacobp100 I've also played around with the Masked View, but that's essentially just the same as giving it `overflow: 'hidden'`, so same issue as the GIF with the weird animation I sent above :/

**Comment by jacobp100** [comment]
What if we put the switch the order of the masked view and context menu?

**Comment by mrousavy** [comment]
@jacobp100 Yeah I've also tried that, doesn't work unfortunately. The masked view essentially acts the same as `overflow: 'hidden'` in this case, since the actual Context Menu preview view has a white background. So we got two cases here:

1. The ContextMenu has borderRadius and overflow hidden (or masked view), and the view inside the context menu has borderRadius 0: It gets shown correctly inside the preview because the preview has it's own borderRadius, but the animation looks weird because the square view gets scaled down inside of the overflow hidden + borderRadius parent
2. The ContextMenu doesn't have anything set but the view inside has a borderRadius: Animation looks good since the borderRadius is actually applied on that view, but Preview has smaller borderRadius and therefore shows white spaces..

**Comment by jacobp100** [comment]
Just to confirm, does it work if you remove the linear gradient and just use a solid background colour on the context menu style?

**Comment by mrousavy** [comment]
no that wouldn't work because the ContextMenu style only the style for the container, not for the preview. The preview view itself is the child of the `<ContextMenu>`.

<img src="https://user-images.githubusercontent.com/15199031/97993879-f4199b80-1de4-11eb-80fd-7dedd95434fc.gif" width="55%">

**Comment by mrousavy** [comment]
It seems to me like the view inside of the preview is wrapped inside of a container which has a white background. (white background can be seen in the first photo I posted) 

I'm wondering if it's possible to remove that background...  🤔

**Comment by jacobp100** [comment]
Okay, I did some digging here.

https://stackoverflow.com/questions/59631151/how-to-hide-uicontextmenuinteraction-uitargetedpreview-black-background

It looks like you need to set a `backgroundColor` and/or `visiblePath` on the preview in some cases.

One idea is we could add a `previewStyle` property that accepts a background colour and/or border radii, and set them on the `UIPreviewParameters`.

The code in RN to get a path for the border radii is already here in [RCTView](https://github.com/facebook/react-native/blob/21349d63f9ba40c4928b62f01a69b4668a7968c5/React/Views/RCTView.m#L879-L901). We should be able to use that for `visiblePath`. `backgroundColor` should be pretty straightforward too.

This could be an alternative to the preview view discussed earlier - so depending on the situation you'll use one or the other (or neither!)

It's still something I can give pointers to, but in terms of sitting down and hashing it out completely is something I don't quite have enough time at the moment to do.

**Comment by mrousavy** [comment]
@jacobp100 thanks for those pointers. To me it has a low priority, but it's going to be the first thing I'm going to focus on after I initially release my app. Thanks!

**Comment by mrousavy** [comment]
@jacobp100 thanks for that link. There was a second answer which showed a way to set a clear background color, I've created a PR for this at https://github.com/mpiannucci/react-native-context-menu-view/pull/16.

@mpiannucci mind taking a quick look at this?

**Comment by mpiannucci** [comment]
Thanks for all the work guys. I have merged in @mrousavy 's changes which look like a great solution for this time. This kinda leads directly into the custom preview content work so its a great start.
