### ISSUE TITLE
ContextMenuView.java compilation errors

### ISSUE THREAD

**Issue by NilsPEA** [mpiannucci/react-native-context-menu-view#115]
Hi!

We recently added the package to our app but have issues compiling for the android-build. We receive the following type of error(s) for the `ContextMenuView.java`-file. 

` local variable i is accessed from within inner class; needs to be declared final`

It applies to three different variables in the file, `i`, `title` & `parentIndex`. It seems to resolve when adding the final keyword to these variables locally and hence we can patch it locally in the meantime. But of course local patching isn't preferred so we would like to request a possible update.

Some data regarding our android setup for easier re-production:
- Most recent package version `1.15.0` (also tried for older version and receive the same error)
- JDK `11`
- React native version `0.66.5`

Thanks in advance!

**Comment by mpiannucci** [comment]
Is there anyway you can try with a fresh project on 0.70 or later? React native has changed a lot since 0.66

**Comment by NilsPEA** [comment]
Sure, I could try either bumping the current project (which will probably show other issues) or just do a fresh project and run it. I'll get back here when I've had the time!

**Comment by NilsPEA** [comment]
Hi! 
So I was able to run a fresh react-native (v0.73.6) project on android with the package successfully. Considering it was a Java error, the bump to a minimum JDK of 17 in the newer react-native version is very likely the culprit.

Thanks for a quick response and sorry for bothering with such an old react-native version 😅 
I'll close the issue!

**Comment by mpiannucci** [comment]
Thanks for reporting and even bigger thanks for reporting the outcome! Cheers!
