### ISSUE TITLE
Add custom preview to iOS

### ISSUE THREAD

**Issue by mwa3aan** [mpiannucci/react-native-context-menu-view#17]
I have written the code to:

Add a property to specify a preview view in your react native app to use as a custom preview on long press in iOS.

Bubble the event back to react native when the preview view is touched.

It isnt a lot of code and very simple.

I will contribute the code for review and enhancements.

**Comment by mpiannucci** [comment]
Awesome, I look forward to taking a look and thank you for the hard work!

**Comment by daxaxelrod** [comment]
Would love to take a look as well! Many apps use context menus that are attached to list items that preview a subsequent screen, iMessage, fb messenger

**Comment by mpiannucci** [comment]
Closed with https://github.com/mpiannucci/react-native-context-menu-view/pull/46

In release version 1.4.0 and up
