### ISSUE TITLE
Support nested menus

### ISSUE THREAD

**Issue by xKRUTOIx** [mpiannucci/react-native-context-menu-view#18]
Hello, thanks for this library : ) 

It will be very useful if this library will support nested menus.

**Comment by mpiannucci** [comment]
CN you give an example of what you are looking for with this? I'm not sure it's possible to do it with uimenu

**Comment by xKRUTOIx** [comment]
@mpiannucci sure, I'm looking for something like this -> https://youtu.be/V2pM9WbpFEA

**Comment by mpiannucci** [comment]
Oh wow! I didnt even know that those were supported in iOS. Ill have a look into it. Thanks for this!

**Comment by mpiannucci** [comment]
I am working on this now btw, hope to have something released either tomorrow or this weekend

**Comment by mpiannucci** [comment]
This is now available in master or from NPM with version `1.2.0`. Thanks!

**Comment by xKRUTOIx** [comment]
Very nice, thanks!
