### ISSUE TITLE
custom icon

### ISSUE THREAD

**Issue by chenxiang39** [mpiannucci/react-native-context-menu-view#26]
i just want custom icon........ help me.....

**Comment by tomgreco** [comment]
+1

**Comment by fukemy** [comment]
+2

**Comment by kostiantyn-ccm** [comment]
+3

**Comment by elouisramsey** [comment]
+4

**Comment by mpiannucci** [comment]
This is next on my list, but I'm not sure the best way to tackle it yet. Stay tuned

**Comment by radekzz** [comment]
+1 This is a decision maker for me

**Comment by SaeedMuhaisen** [comment]
> This is next on my list, but I'm not sure the best way to tackle it yet. Stay tuned

Any updates on this?

**Comment by mpiannucci** [comment]
Now supported in version 1.15.0

**Comment by sraut1** [comment]
@mpiannucci & @wilmxre Thanks for adding this feature and for a great library. Its very difficult to add android icons for expo managed app. any suggestions?

**Comment by wilmxre** [comment]
> @mpiannucci & @wilmxre Thanks for adding this feature and for a great library. Its very difficult to add android icons for expo managed app. any suggestions?

i think there is an expo config plugin that you can use to add drawable resources in android.

**Comment by sraut1** [comment]
Thanks for quick response @wilmxre, I am looking for such plugin but not able to find the good documentation for it.

**Comment by wilmxre** [comment]
take a look at this: https://stackoverflow.com/a/76773373/13582097

you will need to run [expo prebuild](https://docs.expo.dev/workflow/prebuild/) to generate the native ios and android directories (you can add the -p option to only generate the android directory).

you can then add the xml files of the desired icons either by dropping them under `android/app/src/main/res/drawable` manually or by adding a config plugin that will do it for you so you don't have to interact with the native directories at all.

just make sure that after you've generated the directories and added the icons, create a [ custom dev build](https://docs.expo.dev/develop/development-builds/create-a-build/)

**Comment by sraut1** [comment]
Thanks @wilmxre, we do prebuild and generate the native folders but we dont commit them in to the code. I also stumbled upon linked stackoverflow solution that you provided but I was not sure how if it would be a good practice or efficient to modify files on fly. I will give it a shot though. I appreciate the help.

**Comment by alaughlin** [comment]
@sraut1 just curious if you ever figured this out? I am wondering how in the world you add images to xcassets and drawables in expo managed apps. it doesn't seem to be documented anywhere.

**Comment by wilmxre** [comment]
i don't think there is something to lose if you generate the native directories and add them manually. i think the go to way to build expo apps, is by creating custom dev builds, where you get access to the native android and ios folders. using only expo go is very limiting and it is meant to be used only as a quick prototyping tool. 
you can also play around with expo config plugins.

**Comment by wilmxre** [comment]
@sraut1 @alaughlin you should look into this: https://docs.expo.dev/versions/v51.0.0/sdk/asset/#configuration-in-appjsonappconfigjs

**Comment by sraut1** [comment]
@wilmxre Thanks man, I am excited for expo 51 lot of cool features.

**Comment by sraut1** [comment]
@alaughlin try this library: react-native-popup-menu you can customize the pop up menu
