### ISSUE TITLE
Add fallback to ActionSheet?

### ISSUE THREAD

**Issue by adhip94** [mpiannucci/react-native-context-menu-view#31]
Is it possible to add support for ActionSheet for versions below iOS 12 within the library itself?

**Comment by mpiannucci** [comment]
Almost definitely possible

**Comment by mpiannucci** [comment]
This is certainly possible but its a decent amount of work I dont have in me at the moment. Will hopefully revisit soon. but iOS 12 is getting old at this point anyways

**Comment by hirbod** [comment]
I would not waste any time here. The workaround could be build with a little wrapper class around it. Expo for example will stop supporting iOS 12 and increase to iOS13 with SDK 47 (coming in summer)

**Comment by mpiannucci** [comment]
Thanks for the input @hirbod, yeah gunna leave this

**Comment by mpiannucci** [comment]
Not going to do this, this lib is for context menus only
