### ISSUE TITLE
Better view for larger objects

### ISSUE THREAD

**Issue by adhip94** [mpiannucci/react-native-context-menu-view#32]
Currently I am building a chat application using gifted chat. I have integrated the context menu library and it works brilliantly, except for chats with a huge text (50000 characters). An example of a huge text chat is shown below.
![image](https://user-images.githubusercontent.com/20703483/121821534-46923300-ccb7-11eb-91ff-50235ae8476f.jpeg)

On whatsapp even if the text is huge I guess they push the chat message up and show it like below.
![image](https://user-images.githubusercontent.com/20703483/121821569-74777780-ccb7-11eb-96c0-722ba6c5204a.jpeg)

Is this something that can be handled within the library itself or is it something that I need to handle in my application? If so, any suggestions?

**Comment by nucleartux** [comment]
I think with release of preview builder this issue can be also closed. Now you can create small version on content with important content or maybe create scroll view inside preview.

**Comment by mpiannucci** [comment]
Yeha I think with the new preview support this is closed out
