### ISSUE TITLE
Support for React 17

### ISSUE THREAD

**Issue by andreslopezrm** [mpiannucci/react-native-context-menu-view#36]
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.1" from react-native-context-menu-view@1.2.1

I used React Native 0.64 width react 17.0.1

**Comment by BLOCKMATERIAL** [comment]
same problem

**Comment by mpiannucci** [comment]
Ill try and get this updated this weekend, sorry everyone

**Comment by abbasldn** [comment]
same issue here, don't mean to rush you just demonstrating the demand for this issue @mpiannucci

**Comment by mpiannucci** [comment]
An update to support react 17 has been published as version 1.3.0. IF the issue persists, please reopen the issue. Thanks!

**Comment by andreslopezrm** [comment]
That's for you time
