### ISSUE TITLE
Xcode project has broken references 

### ISSUE THREAD

**Issue by Tuuben** [mpiannucci/react-native-context-menu-view#40]
I've been trying to open this library in Xcode but references seems to be all broken. Could this be fixed so it would be possible to open the project locally? Any help appreciated! 😊 

.xcodeproj has missing file references, points to 2 files that doesn't exist. And seems to be no references to any other files contained in the `ios` folder.
![Screenshot 2021-10-29 at 16 52 24](https://user-images.githubusercontent.com/22411478/139447879-2f7096a1-f804-4b98-89ce-15a1a389fbc1.png)

Workspace has reference error to the project as well. Opening the `contents.xcworkspacedata` the workspace points to the wrong xcodeproj
```
<?xml version="1.0" encoding="UTF-8"?>
<Workspace
   version = "1.0">
   <FileRef
     <!-- Points to the wrong .xcodeproj, file is named ReactNativeContextMenuView.xcodeproj -->
      location = "group:ReactNativeContextMenu.xcodeproj">
   </FileRef>
</Workspace>
```

**Comment by mpiannucci** [comment]
Hopefully fixed now.. was able to run and edit from the example project.
