### ISSUE TITLE
actions divider

### ISSUE THREAD

**Issue by kayode0x** [mpiannucci/react-native-context-menu-view#41]
Hi, I feel like adding an actions divider like on the attached image would make it look better. Great job btw!

![IMG_EA218DA229E7-1](https://user-images.githubusercontent.com/60462284/145727739-ed72600e-8aa0-4d5f-b6a0-c41eb565203d.jpeg)

**Comment by kayode0x** [comment]
Got this by passing `inlineChildren: true`

**Comment by mpiannucci** [comment]
Glad you figured it out! If this required changes to native feel free to submit a PR!
