### ISSUE TITLE
"ContextMenu" was not found in the UIManager Error upon component use.

### ISSUE THREAD

**Issue by 25robita** [mpiannucci/react-native-context-menu-view#42]
When using this component I encounter the following error:
```
Invariant Violation: requireNativeComponent: "ContextMenu" was not found in the UIManager.
```
I've tried:
- Restarting computer
- Re-adding and re installing with yarn (I don't use npm)
- A bunch of stuff with pods I can't even remember

**Comment by mpiannucci** [comment]
Closing for now. If this happens again lmk

**Comment by fernando-ropero-akimad** [comment]
same problem
