### ISSUE TITLE
Questions about Android support

### ISSUE THREAD

**Issue by richardgirges** [mpiannucci/react-native-context-menu-view#50]
Hello! We are considering this package for our RN app. We don't currently have a functional Android build so it's difficult for us to test this package for Android. So we had a few questions about Android support:

* Is Android supported?
* What does the Android menu look like?
* Does Android also use SF Symbols? If not, how does `systemIcon` work with Android?

**Comment by mpiannucci** [comment]
Hi!!

* Yes, Android is supported
* On Android menus are rendered as native Android `PopupMenu`s. [See here for an example of what they look like from the SDK](https://www.tutlane.com/tutorial/android/android-popup-menu-with-examples#:~:text=In%20android%2C%20Popup%20Menu%20displays,touch%20outside%20of%20the%20popup.), opr [here is the relevant code](https://www.tutlane.com/tutorial/android/android-popup-menu-with-examples#:~:text=In%20android%2C%20Popup%20Menu%20displays,touch%20outside%20of%20the%20popup.). 
* Android does not use SFSymbols, The `systemIcon` prop is simply ignored on Android and there is no icon shown in the android popup menu. Getting icons into a `PopupMenuItem` on Android is a pain in the ass so it could be done but for me its more of a want than a need. 

I hope this helps

**Comment by richardgirges** [comment]
Amazing, thanks for the prompt and detailed response! We'll be giving the package a go. All concerns addressed, closing ticket.
