### ISSUE TITLE
Checkbox (Active items) support

### ISSUE THREAD

**Issue by Honason** [mpiannucci/react-native-context-menu-view#59]
Thanks for creating such a simple to use library! I really appreciate it. Is there a way to support active items in the menus? The ones with checkmarks, line on this image.

![menu-secondary-actions_2x](https://user-images.githubusercontent.com/2352554/174675677-439a94bb-eafb-4032-879c-eee74b8ff1ca.png)

**Comment by exodusanto** [comment]
I think this one is the feature requested #92

**Comment by mpiannucci** [comment]
Yup this should be available on iOS with the latest version
