### ISSUE TITLE
Invariant Violation: requireNativeComponent: "ContextMenu" was not found in the UIManager

### ISSUE THREAD

**Issue by riledv** [mpiannucci/react-native-context-menu-view#62]
I have same problem:

`Invariant Violation: requireNativeComponent: "ContextMenu" was not found in the UIManager`

Stacktrace:
```
This error is located at:
    in ContextMenu (created by ContextMenu)
    in ContextMenu (created by CellRenderer)
    in RCTView (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by CellRenderer)
    in RCTView (created by View)
    in View (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by TouchableOpacity)
...
```

I am using:
+ ios: 14.5 (reproducible on newer versions too)
+ emulator iphone 12 (reproducible on other versions too)
+ "expo": "46.0.9"
+ "react-native": "0.69.4"

**If I start with `npx expo run:ios` I have not problem, but if I use `npx expo start` I have this problem, when the contextMenu component tries to draw on the screen.**

**Comment by riledv** [comment]
@mpiannucci this question has already been asked and is getting more and more likes https://github.com/mpiannucci/react-native-context-menu-view/issues/42 but it has been closed

**Comment by mpiannucci** [comment]
I havent tested with expo, so thats why i have not addressed this yet

**Comment by jacobp100** [comment]
It's a native module, so it's not going to work with Expo. Think we can just close this

**Comment by riledv** [comment]
It's true, to use with expo you need to run the application via `npx expo run:ios` or `npx expo run:ios --device`
