### ISSUE TITLE
Right click on MacOS causes app crash

### ISSUE THREAD

**Issue by psquizzle** [mpiannucci/react-native-context-menu-view#69]
When an iOS App is run on MacOSM1 using this library. Long press or long click, more specifically does nothing. It fails to trigger long press event. Trying to right click crashes the app.

**Comment by mpiannucci** [comment]
Oh very interesting, I havent tried to use it on M1 yet

**Comment by jacobp100** [comment]
Add a title to the menu - even if it's just an empty string

**Comment by psquizzle** [comment]
Ok, thank you. Setting the optional 'title' prop to an empty string fixed the problem. 

title={""]
