### ISSUE TITLE
What is the event for Context menu onPress?

### ISSUE THREAD

**Issue by MiteshKalal7** [mpiannucci/react-native-context-menu-view#76]
ContextMenu onPress event only fires when we pressed on actions... how can i get an event when the user press on that opened ContextMenu?

**Comment by mpiannucci** [comment]
IM not sure what you mean by this, can you illustrate?

**Comment by MiteshKalal7** [comment]
![Simulator Screen Shot - iPhone 13 - 2023-03-24 at 18 50 01](https://user-images.githubusercontent.com/52530388/227532520-d18a53cb-a1c7-4da1-93c3-af7e99805faf.png)


how do I get the press event for the whole context click?

**Comment by mpiannucci** [comment]
Sorry circling back to this now... By press event do you mean inside of the preview?

**Comment by MiteshKalal7** [comment]
Of course inside of the preview, i want to open full screen when user click on anywhere in context… how can I get that event?

**Comment by mpiannucci** [comment]
Gotcha... not currently exposed but I will add it tomorrow

For myself, implement https://developer.apple.com/documentation/uikit/uicontextmenuinteractiondelegate/3375807-contextmenuinteraction

**Comment by mpiannucci** [comment]
This is now supported in version 1.12.0. Use the `onPreviewPress` prop to get a callback when the user taps the preview on iOS
