### ISSUE TITLE
Support for React 0.72

### ISSUE THREAD

**Issue by andreiwow2** [mpiannucci/react-native-context-menu-view#86]
Hello, React Native 0.72 now uses Gradle 8.0, which changed `classifier` with `archiveClassifier`. I can't build my App anymore with the package.

https://github.com/mpiannucci/react-native-context-menu-view/pull/87

**Comment by mpiannucci** [comment]
Merged. Will test more fromally with my existing stuff soon

**Comment by nicolascavallin** [comment]
Is there an alpha release or something to test it? Thanks in advance <3

**Comment by mpiannucci** [comment]
Pushlied now in version 1.10.0
